name: CI/CD for Backend API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # or your preferred testing command

      - name: Deploy to AWS
        run: |
          sam package --output-template-file packaged.yaml --s3-bucket your-s3-bucket-name
          sam deploy --template-file packaged.yaml --stack-name your-stack-name --capabilities CAPABILITY_IAM
