
name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest discover

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.1.1

        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Format Terraform Files
        run: terraform fmt -recursive

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve tfplan

      - name: Invalidate CloudFront Cache (Optional for Frontend)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3K9N6AT08YG7J \
            --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
