name: CI/CD for Backend

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your desired region

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0  # Replace with your desired Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Import Existing Resources
      run: |
        terraform import aws_iam_role.lambda_execut_role lambda_execut_role || echo "Role already managed"
        terraform import aws_dynamodb_table.VisitorCounter VisitorCounter || echo "Table already managed"
        terraform import aws_lambda_function.visitor_counter_function VisitorCounterFunction || echo "Function already managed"
        terraform import aws_iam_policy.lambda_dynamo_policy arn:aws:iam::905418480080:policy/lambda_dynamo_policy || echo "Policy already managed"
        terraform import aws_lambda_permission.api_gateway_invoke_lambda VisitorCounterFunction || echo "Permission already managed"

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Install dependencies for tests
      run: |
        python -m pip install --upgrade pip
        pip install moto boto3

    - name: Run Tests
      run: |
        python -m unittest discover -s tests  # Adjust the path to where your tests are located

    - name: Create CloudFront Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
