name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set your Python version here

      - name: Install dependencies
        run: |
          pip install boto3  # Install any dependencies your Lambda function needs

      - name: Package Lambda function
        run: |
          zip -r function.zip lambda_function.py  # Include any additional files if necessary

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your region

      - name: Initialize Terraform
        run: |
          cd terraform  # Change to your Terraform directory if different
          terraform init

      - name: Apply Terraform changes
        run: |
          cd terraform  # Change to your Terraform directory if different
          terraform apply -auto-approve

      - name: Create CloudFront Invalidation
        run: |
         aws cloudfront create-invalidation --distribution-id E3K9N6AT08YG7J --paths "/*"
